export default {
  login: "auth/login",
  register: "auth/register",
  refresh_token: "auth/refresh",
  get_me: "users/me",
  purchases: "purchases",
  customers: "customers/find-or-create",
  customers_list: "customers/list",
  get_details: "customers/get-details",
  updated_customer_update: "customers/update",
  points_redeem: "redemptions/redeem",
  redemptions_list: "redemptions",
  customer_points_history: "customers/ledger",
  coupons: "coupons",
};
