export default {
  login: "auth/login",
  register: "auth/register",
  refresh_token: "auth/refresh",
  forgot_password: "auth/forgot-password",
  verify_otp: "auth/verify-otp",
  reset_password: "auth/reset-password",

  get_me: "users/me",
  purchases: "purchases",
  customers: "customers/find-or-create",
  customers_list: "customers/list",
  get_details: "customers/get-details",
  updated_customer_update: "customers/update",
  points_redeem: "redemptions/redeem",
  redemptions_list: "redemptions",
  customer_points_history: "customers/ledger",
  coupons: "coupons",
  coupons_validate: "coupons/validate",
  coupons_redeem: "coupons/redeem",
};
